title: "My New Site"
subtitle: "A Website For Me!"
packs:
- "jules:html5boilerplate"
- "jules:lesscss"
- "jules:atom"
- "jules:pygments"
- "dir:templates"
- "dir:static"
- "dir:contents"
google_analytics_id: "UA-XXXXXX-XX"
domain: "www.example.com"
default_author: "You <you@example.com>"
ignore:
- "*.swp"
- "*.swo"
- "~*"
bundle_defaults:
    output_ext: ""
    render: jinja2
collections:
    tags:
        key_pattern: "{value}"
        match:
            status: published
        group_by:
            in: tags
        meta:
            render: jinja2
            template: tag.j2
