title: "My New Site"
subtitle: "A Website For Me!"
packs:
- "jules:html5boilerplate"
- "jules:lesscss"
- "jules:atom"
- "jules:pygments"
- "dir:templates"
- "dir:static"
- "dir:contents"
google_analytics_id: "UA-XXXXXX-XX"
domain: "www.example.com"
default_author: "You <you@example.com>"
tag_path: "tags/{tag}/"
